Vagrant.configure("2") do |config|

  # VM image
  config.vm.box = "ubuntu/focal64"

  # Network
  config.vm.network "forwarded_port", guest: 8000, host: 8000

  # Syncing the application folder
  config.vm.synced_folder "../jokes_api/src", "/vagrant/app"

  # Syncing requirements.txt
  config.vm.synced_folder "../requirements.txt", "/vagrant/requirements.txt"

 # Defining ansible as the installer
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "playbook.yml"
  end

end